### ISSUE TITLE
KeyError: 'emailAddresses'

### ISSUE THREAD

**Issue by Vip3rLi0n** [WildSiphon/Mailfogle#3]
Got this error when trying to run the script:
```py
Connected to Google people API
Traceback (most recent call last):
  File "C:\Users\Nizzy\Mailfogle\mailfogle.py", line 139, in <module>
    main()
  File "C:\Users\Nizzy\Mailfogle\mailfogle.py", line 101, in main
    mail = person['emailAddresses'][0]['value']
KeyError: 'emailAddresses'
```

How to fix this?

**Comment by WildSiphon** [comment]
**What you should know**

`connections` is an array of all the contacts from the google account used
`for person in connections` iterate all the downloaded contacts

Normally the Google People API returns a dict of dict with all the contact's information. The field `['emailAddresses'][0]['value']` is used to know which address we're currently working on before searching inside (if it is actually in the file `emails.txt`).

Even if you put a wrong address in `emails.txt`, the field is supposed to exist.

**What you could do**
+ Did you add `Google People API` to your project in https://console.cloud.google.com/ ?
If you're not sure see `CONFIGURE_API.md` which explains step-by-step what to do.
+ If you're sure that everything is set up correctly, try to delete `token.json` and do the connection again.
+ If that doesn't work either, regenerate `OAuth client ID`.

**If it doesn't work**

I don't know how to reproduce this error by myself so I just gave you generic clue to solve it.
If the error is still here after that, could you to add a print statement line 101 and answer with te output ? I would like to see what the API is giving back to you

Like this :
```python
for person in connections:
  data = {}
  print(person)
  mail = person['emailAddresses'][0]['value']
```


**Watch out**

Everytime you run the script before it crash, a new email address is added to the account contact's list and not deleted (I will add a fix to this). I'll suggest to you to go on [this page](https://contacts.google.com/) and manage all the address you don't want to keep.

**Comment by WildSiphon** [comment]
After further investigations from a friend, this bug is corrected. You will not see it again
